name: Tests

on:
  push:
    paths:
      - 'dict_toolset/**'
      - 'tests/**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'dict_toolset/**'
      - 'tests/**'
      - '.github/workflows/**'

permissions:
  id-token: write
  contents: read
  checks: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12-dev"]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install dependencies
      run: |
        pip install unittest-xml-reporting
    - name: Run tests
      run: |
        python tests
    
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Python Unit Tests
        path: test-reports/*.xml
        reporter: java-junit
